CREATE TABLE music_album(
  id INT GENERATED ALWAYS AS IDENTITY,
  on_spotify BOOLEAN NOT NULL,
  PRIMARY KEY (id),
  CONSTRAINT fk_music_album
    FOREIGN KEY (id) REFERENCES item(id)
    ON DELETE RESTRICT ON UPDATE CASCADE,
)

CREATE TABLE genre (
  id INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);
